# Generated by Django 4.1.5 on 2023-08-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cover_me_app", "0002_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(default="resume_text")),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="coverletter",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
