# Generated by Django 4.1.5 on 2023-08-18 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cover_me_app", "0003_resume_alter_coverletter_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="job",
            name="title",
        ),
    ]
