# Generated by Django 4.1.5 on 2023-08-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cover_me_app", "0004_remove_job_location_remove_job_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, default="unknown", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(default="Default Title", max_length=250),
        ),
    ]
